
services:
    database:
        container_name: mysql-container
        image: mysql/mysql-server:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: teste_cadastros
            MYSQL_USER: MySQLUser
            MYSQL_PASSWORD: MySqlPassword